### ISSUE TITLE
help with the code needed

### ISSUE THREAD

**Issue by noobed7** [koralium/OPADotNet#50]
Hello,
I am stuck reading and understanding some parts of the code of this repo. Would appreciate some help with the following:
1) OpaInput - only allows a Request in the form of a URI. I reckon it won't be possible to structure it in the form of a resource-action pair?
2) Is it a better approach to use a RegoWrapper and bundling it with a RegoSdk.dll than using a .wasm module?
3) How do the sync classes work exactly - can't wrap my head around them 😞 
4) DiscoverySyncBuilder vs SyncBuilder
5) how do expressions work - as stated in the readme - It also features a way to translate OPA partial queries to C# expressions that can be used to pass down permissions through EntityFrameworkCore.

###### p.s. this issue represent my inability to find any emails or publicly available means to reach any of the developers. If this text is not suitable for a github issue - please, reach out to me by email - linked on my account bio

**Comment by Ulimo** [comment]
Hi, 

Regarding point 1:
The idea for OpaInput was to use the extensions:
https://github.com/koralium/OPADotNet/blob/23d68d5c90d1ee032dd8c1ddb4561a5f00b9388b/netcore/src/OPADotNet.AspNetCore/Input/OpaInput.cs#L39

To add any data that one would require. These are a jsonextension so it will be added to the json object.
This can ofcourse be subject to change if its not working.

2. Wasm does not support partial evaluation which is required to create C# expressions that can be pushed down to databases. 
3. DiscoverySync was meant to follow: https://www.openpolicyagent.org/docs/v0.12.2/discovery/ to allow to get in other bundles.
4. SyncBuilder allows one to set up syncs of policy and data, for example against an OPA server or Azure Storage. Example: https://opadotnet.readthedocs.io/en/latest/remotes/opaserversync.html https://opadotnet.readthedocs.io/en/latest/remotes/targzsync.html
5. At this time alot of the framework is set up for AspNetCore, there is an example in samples https://github.com/koralium/OPADotNet/blob/b4f6d749bcb4f42a9a872e183c06775638a4c09b/samples/MvcExample/Controllers/DataController.cs#L43 on how to add a where statement against an IQueryable.

If you do not plan to use AspNetCore there is probably some extra samples etc that needs to be added. So if you could explain a bit of your case that would be great :)

**Comment by Ulimo** [comment]
Hi @noobed7 is this still something you need help with?

**Comment by noobed7** [comment]
Hi @Ulimo , sorry for not getting back to you sooner. You answer was very helpful and helped me figure out lots of the puzzle. 
I was researching how it would be best to make most of OPA in our .net ecosystem. We are facing a set of microservices on Azure SF and a bunch of standalone backends. We are still on the research phase and looking through different nugets and their code (if available). 
I don't have any more questions so I might as well mark it as a closed :~) 
Thank you
